insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Home Furniture', 11084, 8146);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Rent Deposit', 25390, 4519);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Wedding Fund', 2530, 9304);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Concert Tickets', 121093, 5672);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'House Down Payment', 115549, 5002);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Birthday Celebration', 4920, 952);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Education Fund', 15388, 390);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Home Appliances', 233, 614);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Concert Tickets', 6681, 96609);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Dream Travel Fund', 1898, 52692);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Investment Portfolio', 50000, 4708);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Debt-Free Goal', 5039, 688);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Emergency Fund', 50872, 9200);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Car Repairs', 8422, 6122);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'House Down Payment', 24120, 16501);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Concert Tickets', 17241, 19078);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Concert Tickets', 12856, 90043);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Rent Deposit', 32853, 2508);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Future Baby Expenses', 111708, 18383);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Rent Deposit', 4146, 19556);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Back-to-School Supplies', 93266, 64887);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Home Furniture', 119326, 74475);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Wedding Fund', 33672, 6267);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Future Baby Expenses', 39415, 96907);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Children''s College Fund', 13405, 86679);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Children''s College Fund', 97605, 83257);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Wedding Fund', 122311, 37606);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Rent Deposit', 121030, 50569);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Concert Tickets', 118804, 10497);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Future Baby Expenses', 116148, 14930);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Professional Certification', 107427, 69131);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Rent Deposit', 53611, 22978);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Professional Certification', 24721, 32825);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Vacation Trip', 76298, 69555);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Dream Travel Fund', 88167, 49162);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Concert Tickets', 94373, 70311);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Retirement Fund', 8281, 72118);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Home Appliances', 39011, 5342);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Home Appliances', 58658, 77300);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Dream Travel Fund', 43813, 34822);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'New Car', 96167, 13012);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Vacation Trip', 46153, 14058);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Debt-Free Goal', 38673, 60633);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Home Furniture', 90846, 87121);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Education Fund', 112935, 9276);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Future Baby Expenses', 45580, 29151);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Back-to-School Supplies', 34129, 68201);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Professional Certification', 98384, 58840);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Investment Portfolio', 25368, 36829);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Home Furniture', 106037, 39436);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'House Down Payment', 88082, 68797);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Business Startup', 101755, 50389);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Wedding Fund', 56850, 56152);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Back-to-School Supplies', 54669, 12);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Business Startup', 26572, 24189);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Wedding Fund', 106386, 4772);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Emergency Fund', 96035, 91180);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Future Baby Expenses', 46061, 86815);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Investment Portfolio', 20306, 78009);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Emergency Fund', 101914, 86252);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Holiday Gifts', 85485, 83505);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Birthday Celebration', 88797, 9961);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Professional Certification', 3237, 87556);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Wedding Fund', 23119, 88147);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Back-to-School Supplies', 23295, 19368);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Investment Portfolio', 92892, 90313);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'New Laptop', 70306, 87283);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Car Repairs', 122890, 98028);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Debt-Free Goal', 20682, 8244);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Holiday Gifts', 4086, 57349);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Investment Portfolio', 15917, 93520);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Holiday Gifts', 97400, 23598);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'New Phone', 81158, 79454);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'New Car', 122775, 34473);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Wedding Fund', 120396, 92662);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Birthday Celebration', 87234, 17713);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Professional Certification', 9162, 303);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'New Car', 3451, 18147);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'House Down Payment', 65282, 53540);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Business Startup', 60902, 33358);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Vacation Trip', 76407, 96752);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Retirement Fund', 27138, 21899);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'New Phone', 34316, 63843);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Investment Portfolio', 59018, 31763);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Emergency Fund', 94934, 29118);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Concert Tickets', 110328, 36558);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Retirement Fund', 76924, 12483);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Dream Travel Fund', 41472, 31274);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Back-to-School Supplies', 72645, 21414);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'New Laptop', 34504, 19723);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'New Laptop', 107752, 75315);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'New Laptop', 70153, 63418);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Debt-Free Goal', 94911, 41851);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Vacation Trip', 87098, 79256);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Investment Portfolio', 90377, 44580);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Back-to-School Supplies', 119133, 64726);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Home Furniture', 33370, 51464);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Home Furniture', 29283, 17193);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Education Fund', 108073, 76429);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Professional Certification', 89295, 94962);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Car Repairs', 78839, 26846);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Education Fund', 56026, 57774);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Education Fund', 120248, 84530);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Business Startup', 52704, 97322);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'New Laptop', 68030, 57135);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'New Phone', 29725, 35398);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'New Car', 32213, 1026);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'New Laptop', 14063, 33437);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Children''s College Fund', 5714, 49547);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Birthday Celebration', 9032, 89795);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Investment Portfolio', 52671, 61199);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Home Furniture', 24354, 76483);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'New Phone', 21416, 12211);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Debt-Free Goal', 58688, 33176);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'House Down Payment', 32804, 67121);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'House Down Payment', 74572, 45527);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'New Phone', 29401, 23824);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'House Down Payment', 32032, 74625);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'New Car', 78638, 54784);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Back-to-School Supplies', 25299, 60213);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'House Down Payment', 91768, 99498);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Dream Travel Fund', 11359, 88661);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Holiday Gifts', 52592, 28785);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Future Baby Expenses', 90503, 88550);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Children''s College Fund', 18239, 25339);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Birthday Celebration', 94646, 18370);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Children''s College Fund', 41887, 28363);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Dream Travel Fund', 81581, 51819);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Vacation Trip', 115201, 1738);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Professional Certification', 119737, 81782);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Retirement Fund', 65712, 31688);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Dream Travel Fund', 57977, 60548);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'House Down Payment', 58540, 62678);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Rent Deposit', 72253, 69053);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Home Furniture', 65141, 30659);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Home Appliances', 14721, 66414);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Children''s College Fund', 7908, 4692);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Children''s College Fund', 84390, 51993);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Birthday Celebration', 79041, 45653);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Birthday Celebration', 1723, 77786);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Car Repairs', 23108, 64207);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Debt-Free Goal', 107539, 82409);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Wedding Fund', 709, 51551);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Professional Certification', 116020, 81639);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Education Fund', 24474, 86120);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Future Baby Expenses', 115022, 48897);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Car Repairs', 33333, 58480);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Dream Travel Fund', 118506, 25274);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Education Fund', 43074, 46286);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Birthday Celebration', 115259, 60592);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Concert Tickets', 25762, 17089);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Debt-Free Goal', 91374, 39931);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'House Down Payment', 19760, 28514);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Birthday Celebration', 19324, 60427);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'New Phone', 45920, 23052);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Children''s College Fund', 118748, 43921);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Concert Tickets', 41926, 60494);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Wedding Fund', 86508, 60844);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Birthday Celebration', 38316, 75695);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'New Laptop', 11439, 28144);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Dream Travel Fund', 28567, 34549);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Concert Tickets', 93842, 63440);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Holiday Gifts', 100542, 72259);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'New Phone', 43764, 78499);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Home Furniture', 16140, 91643);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Home Appliances', 61422, 65128);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Dream Travel Fund', 84269, 84322);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Holiday Gifts', 88452, 68983);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Future Baby Expenses', 71387, 41049);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Holiday Gifts', 84953, 79019);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Future Baby Expenses', 24444, 18368);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'House Down Payment', 102541, 22904);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Car Repairs', 114512, 32921);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Holiday Gifts', 70232, 45100);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Vacation Trip', 21345, 91325);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Dream Travel Fund', 59936, 38912);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Rent Deposit', 763, 84477);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Future Baby Expenses', 94475, 31081);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Birthday Celebration', 95860, 54199);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Wedding Fund', 44072, 11822);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'New Phone', 17497, 161);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'New Laptop', 85119, 74154);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Concert Tickets', 21719, 95140);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Home Furniture', 76173, 81407);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Business Startup', 27742, 5334);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Holiday Gifts', 66698, 81343);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Debt-Free Goal', 9686, 26132);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Rent Deposit', 13051, 44817);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Retirement Fund', 6893, 66696);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Wedding Fund', 99636, 74713);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Dream Travel Fund', 74127, 61406);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Education Fund', 103518, 38598);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Professional Certification', 64509, 71691);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Back-to-School Supplies', 93488, 64254);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'New Laptop', 15971, 72708);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Rent Deposit', 16726, 101);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Car Repairs', 1252, 934);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Investment Portfolio', 3873, 80786);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Debt-Free Goal', 59576, 72806);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Rent Deposit', 85656, 97539);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Dream Travel Fund', 109621, 29712);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'New Phone', 93570, 59331);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Education Fund', 100040, 52986);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Wedding Fund', 112023, 62411);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Retirement Fund', 5257, 39175);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Professional Certification', 116734, 9892);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Children''s College Fund', 14018, 731);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Business Startup', 48745, 15000);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Car Repairs', 28584, 11114);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Emergency Fund', 68264, 57338);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Emergency Fund', 25584, 81537);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Retirement Fund', 44716, 33209);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Holiday Gifts', 1815, 679);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Debt-Free Goal', 52000, 87442);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Vacation Trip', 25145, 96785);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Wedding Fund', 17204, 55700);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Retirement Fund', 34262, 20254);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'New Laptop', 10052, 51552);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Birthday Celebration', 29976, 27527);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Business Startup', 94149, 64785);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Home Furniture', 107838, 28499);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Investment Portfolio', 80215, 84739);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Investment Portfolio', 75171, 107);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Professional Certification', 5461, 13719);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Investment Portfolio', 86442, 95413);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Birthday Celebration', 17361, 70306);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Education Fund', 105742, 69387);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'New Phone', 56614, 714);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Wedding Fund', 49577, 29580);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Investment Portfolio', 8291, 18756);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Birthday Celebration', 5000, 500);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Home Furniture', 73471, 8845);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'New Laptop', 6900, 1341);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Wedding Fund', 22166, 5370);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Children''s College Fund', 81506, 6944);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'Investment Portfolio', 29848, 99754);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Rent Deposit', 94542, 58696);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Birthday Celebration', 37427, 26525);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Birthday Celebration', 114814, 32744);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Rent Deposit', 70551, 33907);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'New Phone', 83310, 82420);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Business Startup', 19772, 50956);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Vacation Trip', 97104, 67189);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Investment Portfolio', 76741, 92685);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Professional Certification', 35953, 74548);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Education Fund', 18969, 86615);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Rent Deposit', 101436, 86972);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Business Startup', 10000, 5194);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Wedding Fund', 110114, 83231);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Professional Certification', 74265, 26228);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Children''s College Fund', 93082, 23254);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Dream Travel Fund', 23219, 71401);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Home Appliances', 113004, 43275);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Holiday Gifts', 55188, 40312);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Future Baby Expenses', 30389, 92658);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'New Laptop', 29406, 60384);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Education Fund', 61044, 14482);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Holiday Gifts', 117383, 56120);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'New Phone', 5999, 57448);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (4, 'Business Startup', 63707, 1904);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Education Fund', 122415, 71365);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Birthday Celebration', 46744, 26742);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Vacation Trip', 15069, 94263);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Dream Travel Fund', 58307, 71622);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Education Fund', 1396, 94101);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'House Down Payment', 104828, 1532);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Home Furniture', 101413, 65474);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Birthday Celebration', 81828, 75340);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Holiday Gifts', 63037, 99642);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (10, 'New Phone', 18039, 36975);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Concert Tickets', 14840, 5989);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Debt-Free Goal', 20418, 53619);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Birthday Celebration', 22612, 12461);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Holiday Gifts', 52049, 7908);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Rent Deposit', 34078, 42036);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Birthday Celebration', 115294, 86097);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Concert Tickets', 98583, 36211);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Professional Certification', 95747, 62244);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Business Startup', 117860, 12825);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Home Furniture', 62013, 93336);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Emergency Fund', 118850, 21188);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Wedding Fund', 112935, 39155);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (8, 'Rent Deposit', 97311, 46764);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Rent Deposit', 3500, 3000);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (5, 'Rent Deposit', 8500, 6700);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Home Appliances', 23897, 18392);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (7, 'Dream Travel Fund', 1963, 1200);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (3, 'Rent Deposit', 10273, 3040);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (6, 'Professional Certification', 20845, 5990);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (9, 'Dream Travel Fund', 109154, 13948);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (2, 'Holiday Gifts', 2980, 2000);
insert into SavingGoals (user_id, goal_name, target_amount, current_amount) values (1, 'Wedding Fund', 50745, 25000);
