INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Home Furniture', 11084, 8146);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Rent Deposit', 2500, 1900);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Wedding Fund', 25000, 9300);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Dream Travel Fund', 1898, 52692);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Debt-Free Goal', 5039, 688);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Car Repairs', 8422, 6122);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Concert Tickets', 94373, 70311);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Vacation Trip', 46153, 14058);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Investment Portfolio', 25000, 10000);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'House Down Payment', 88082, 68797);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Holiday Gifts', 8000, 5000);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Birthday Celebration', 8000, 2500);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Wedding Fund', 106000, 4772);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (1, 'Vacation Trip', 10000, 6752);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (2, 'Concert Tickets', 17241, 19078);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (2, 'Future Baby Expenses', 39415, 96907);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (2, 'New Car', 96167, 13012);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (2, 'Emergency Fund', 96035, 91180);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (2, 'Investment Portfolio', 90377, 44580);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (2, 'Back-to-School Supplies', 1133, 726);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (2, 'Professional Certification', 895, 500);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (3, 'Future Baby Expenses', 11122, 1383);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (3, 'Rent Deposit', 4146, 19556);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (3, 'Concert Tickets', 1804, 1600);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (3, 'Home Appliances', 58658, 77300);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (3, 'Back-to-School Supplies', 295, 168);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (3, 'Investment Portfolio', 15917, 93520);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (3, 'Professional Certification', 9162, 303);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (4, 'House Down Payment', 115549, 5002);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (4, 'Education Fund', 15388, 390);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (4, 'Wedding Fund', 33672, 6267);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (4, 'Retirement Fund', 8281, 72118);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (4, 'Debt-Free Goal', 38673, 60633);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (4, 'Future Baby Expenses', 45580, 29151);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (4, 'Back-to-School Supplies', 34129, 68201);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (4, 'New Phone', 81158, 79454);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (4, 'New Car', 3451, 18147);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (5, 'Children''s College Fund', 97605, 83257);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (5, 'Professional Certification', 98384, 58840);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (5, 'Emergency Fund', 101914, 86252);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (5, 'Investment Portfolio', 92892, 90313);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (5, 'Back-to-School Supplies', 72645, 21414);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (5, 'New Laptop', 107752, 75315);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (5, 'Debt-Free Goal', 94911, 41851);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (6, 'Concert Tickets', 12856, 90043);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (6, 'Back-to-School Supplies', 93266, 64887);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (6, 'Wedding Fund', 12000, 37606);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (6, 'Investment Portfolio', 20306, 78009);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (6, 'Debt-Free Goal', 20682, 8244);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (6, 'Holiday Gifts', 97400, 23598);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'Concert Tickets', 1090, 672);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'Home Appliances', 233, 614);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'Rent Deposit', 32853, 2508);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'House Down Payment', 24120, 16501);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'Professional Certification', 107427, 69131);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'Vacation Trip', 7008, 6555);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'Business Startup', 101755, 50389);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'Back-to-School Supplies', 54669, 12);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'New Laptop', 70306, 87283);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'Car Repairs', 122890, 98028);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'Holiday Gifts', 4086, 57349);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (7, 'Emergency Fund', 94934, 29118);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (8, 'Retirement Fund', 27138, 21899);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (8, 'New Phone', 34316, 63843);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (8, 'Dream Travel Fund', 41472, 31274);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (8, 'Home Furniture', 33370, 51464);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (9, 'Education Fund', 108073, 76429);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (10, 'Business Startup', 60902, 33358);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (10, 'Retirement Fund', 76924, 12483);
INSERT INTO SavingGoals (user_id, goal_name, target_amount, current_amount) VALUES (10, 'New Laptop', 34504, 19723);
