insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (1, 14, 252, 1, '2024-08-04', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (2, 8, 353, 6, '2025-02-07', 'Costco');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (3, 7, 317, 3, '2025-02-06', 'Whole Foods');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (4, 15, 396, 1, '2025-01-27', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (5, 4, 434, 6, '2025-02-17', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (6, 7, 302, 9, '2025-03-21', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (7, 4, 295, 2, '2024-12-20', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (8, 1, 165, 7, '2024-12-05', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (9, 4, 101, 5, '2024-10-18', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (10, 14, 133, 6, '2024-07-21', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (11, 1, 354, 4, '2024-11-10', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (12, 1, 33, 2, '2024-08-26', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (13, 6, 94, 5, '2025-01-03', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (14, 8, 77, 3, '2024-10-21', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (15, 13, 170, 1, '2024-12-17', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (16, 10, 277, 5, '2024-12-22', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (17, 5, 45, 1, '2025-01-30', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (18, 9, 101, 8, '2025-03-19', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (19, 6, 261, 8, '2025-04-14', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (20, 13, 486, 3, '2024-11-12', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (21, 9, 77, 6, '2024-06-02', 'Macy’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (22, 13, 104, 2, '2024-08-06', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (23, 9, 191, 1, '2025-03-22', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (24, 4, 497, 5, '2024-12-16', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (25, 10, 452, 1, '2025-01-05', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (26, 12, 497, 1, '2024-11-07', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (27, 6, 459, 8, '2025-04-04', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (28, 14, 99, 4, '2024-12-23', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (29, 6, 225, 5, '2024-09-18', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (30, 14, 34, 8, '2025-02-27', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (31, 6, 474, 5, '2025-04-02', 'Whole Foods');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (32, 7, 411, 1, '2024-12-31', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (33, 1, 337, 4, '2025-01-15', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (34, 12, 458, 4, '2025-01-28', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (35, 4, 351, 7, '2024-12-20', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (36, 10, 452, 3, '2025-02-08', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (37, 10, 398, 5, '2024-10-05', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (38, 6, 435, 7, '2025-02-19', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (39, 3, 267, 7, '2024-07-02', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (40, 1, 283, 9, '2024-07-17', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (41, 5, 286, 5, '2024-09-09', 'Macy’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (42, 1, 132, 3, '2024-10-26', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (43, 15, 82, 1, '2024-06-14', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (44, 8, 267, 3, '2025-04-05', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (45, 4, 389, 6, '2024-12-15', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (46, 7, 56, 2, '2025-02-12', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (47, 14, 114, 7, '2024-08-16', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (48, 8, 13, 1, '2024-10-09', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (49, 12, 120, 8, '2025-04-02', 'Macy’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (50, 11, 376, 3, '2025-02-09', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (51, 1, 102, 4, '2025-01-04', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (52, 6, 306, 9, '2024-10-19', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (53, 6, 392, 8, '2024-10-12', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (54, 14, 84, 6, '2024-11-15', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (55, 7, 216, 9, '2024-08-09', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (56, 15, 235, 8, '2024-11-05', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (57, 10, 302, 4, '2024-12-11', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (58, 3, 435, 10, '2024-08-28', 'Macy’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (59, 4, 249, 4, '2024-08-03', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (60, 2, 391, 9, '2024-10-12', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (61, 2, 333, 3, '2024-12-06', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (62, 6, 267, 6, '2025-01-05', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (63, 5, 379, 4, '2024-12-24', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (64, 15, 158, 3, '2024-07-09', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (65, 8, 50, 7, '2024-11-14', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (66, 2, 90, 2, '2024-12-01', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (67, 12, 107, 4, '2024-09-06', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (68, 11, 51, 7, '2024-07-21', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (69, 13, 305, 3, '2024-09-21', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (70, 11, 266, 10, '2024-10-31', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (71, 10, 13, 6, '2025-02-22', 'CVS');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (72, 15, 77, 7, '2024-09-05', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (73, 5, 317, 4, '2024-11-30', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (74, 15, 111, 5, '2024-08-04', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (75, 11, 163, 1, '2024-06-21', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (76, 4, 186, 6, '2024-08-04', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (77, 3, 494, 9, '2024-06-15', 'Macy’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (78, 9, 236, 2, '2024-12-23', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (79, 14, 8, 4, '2025-03-12', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (80, 9, 381, 2, '2024-12-01', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (81, 14, 500, 1, '2024-12-25', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (82, 10, 188, 4, '2025-03-26', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (83, 11, 37, 1, '2024-09-19', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (84, 9, 498, 1, '2024-08-27', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (85, 5, 183, 4, '2025-01-22', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (86, 14, 175, 4, '2024-11-09', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (87, 14, 259, 1, '2025-02-23', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (88, 8, 293, 1, '2025-03-08', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (89, 12, 401, 6, '2024-09-30', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (90, 6, 419, 1, '2024-10-07', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (91, 13, 98, 1, '2024-12-27', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (92, 7, 418, 9, '2024-07-09', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (93, 14, 69, 7, '2025-02-19', 'Macy’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (94, 13, 159, 2, '2025-01-17', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (95, 11, 2, 4, '2024-12-27', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (96, 9, 466, 5, '2025-03-23', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (97, 7, 274, 3, '2024-08-27', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (98, 6, 415, 3, '2025-01-17', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (99, 13, 282, 2, '2024-08-18', 'CVS');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (100, 3, 478, 2, '2024-06-24', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (101, 1, 25, 7, '2024-07-26', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (102, 1, 66, 4, '2024-07-28', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (103, 15, 345, 10, '2024-08-17', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (104, 3, 106, 7, '2025-02-11', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (105, 11, 269, 2, '2024-12-17', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (106, 12, 342, 8, '2024-06-25', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (107, 10, 193, 9, '2025-02-17', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (108, 4, 210, 5, '2024-10-04', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (109, 3, 182, 2, '2025-02-22', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (110, 14, 475, 7, '2025-01-14', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (111, 12, 53, 10, '2025-03-06', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (112, 3, 139, 8, '2025-01-21', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (113, 7, 389, 7, '2025-02-14', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (114, 5, 58, 9, '2025-01-09', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (115, 14, 79, 9, '2024-12-18', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (116, 15, 212, 7, '2025-02-07', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (117, 12, 346, 1, '2024-07-19', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (118, 2, 104, 10, '2024-11-18', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (119, 12, 18, 8, '2024-08-29', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (120, 11, 138, 8, '2024-12-22', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (121, 13, 99, 8, '2025-04-19', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (122, 1, 438, 9, '2024-06-13', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (123, 12, 444, 9, '2025-03-16', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (124, 1, 351, 10, '2024-08-16', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (125, 2, 395, 6, '2025-04-12', 'Costco');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (126, 8, 226, 4, '2025-02-24', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (127, 1, 76, 5, '2025-01-20', 'Costco');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (128, 5, 302, 6, '2025-01-17', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (129, 4, 115, 4, '2024-11-26', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (130, 6, 196, 2, '2024-11-30', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (131, 2, 205, 7, '2024-06-10', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (132, 7, 467, 6, '2024-08-17', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (133, 6, 26, 10, '2025-03-24', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (134, 14, 403, 8, '2024-12-13', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (135, 5, 267, 4, '2024-11-04', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (136, 12, 418, 6, '2024-12-19', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (137, 14, 488, 9, '2024-09-25', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (138, 8, 200, 2, '2024-08-27', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (139, 12, 294, 9, '2024-11-03', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (140, 10, 205, 7, '2024-06-15', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (141, 10, 179, 7, '2025-04-02', 'CVS');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (142, 15, 258, 6, '2024-08-14', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (143, 1, 280, 5, '2024-12-24', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (144, 14, 297, 2, '2024-09-29', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (145, 4, 407, 1, '2024-11-14', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (146, 2, 392, 5, '2025-03-14', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (147, 5, 138, 1, '2024-12-01', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (148, 1, 224, 4, '2025-03-18', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (149, 9, 298, 9, '2024-09-27', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (150, 6, 309, 5, '2025-01-15', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (151, 4, 442, 9, '2024-12-27', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (152, 1, 209, 3, '2025-03-31', 'CVS');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (153, 10, 195, 4, '2024-11-02', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (154, 12, 79, 10, '2025-01-19', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (155, 3, 401, 3, '2024-06-25', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (156, 8, 223, 9, '2025-04-09', 'Whole Foods');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (157, 11, 130, 5, '2024-12-30', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (158, 15, 379, 1, '2025-03-10', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (159, 8, 227, 9, '2024-11-28', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (160, 13, 182, 10, '2024-08-14', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (161, 15, 135, 7, '2024-08-26', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (162, 11, 300, 6, '2025-03-06', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (163, 15, 280, 4, '2024-11-16', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (164, 5, 425, 9, '2024-06-29', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (165, 2, 264, 2, '2025-01-28', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (166, 9, 99, 1, '2024-11-03', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (167, 8, 260, 7, '2025-04-05', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (168, 12, 153, 2, '2024-12-19', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (169, 12, 383, 7, '2024-12-18', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (170, 7, 336, 6, '2024-08-15', 'Costco');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (171, 10, 114, 3, '2025-01-09', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (172, 9, 387, 8, '2024-07-05', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (173, 12, 90, 6, '2024-09-30', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (174, 15, 358, 9, '2024-09-21', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (175, 4, 123, 2, '2024-10-15', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (176, 9, 363, 9, '2025-01-23', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (177, 13, 179, 3, '2024-10-20', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (178, 9, 98, 9, '2024-09-19', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (179, 15, 432, 5, '2024-11-25', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (180, 6, 55, 7, '2024-06-20', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (181, 12, 391, 5, '2024-11-25', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (182, 11, 129, 4, '2024-11-13', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (183, 3, 479, 10, '2024-06-16', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (184, 1, 403, 10, '2024-11-08', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (185, 10, 304, 10, '2024-12-27', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (186, 1, 418, 2, '2024-07-24', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (187, 1, 420, 7, '2025-04-17', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (188, 9, 354, 8, '2024-06-24', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (189, 5, 37, 2, '2024-10-13', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (190, 13, 448, 1, '2024-10-11', 'Costco');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (191, 8, 26, 5, '2024-10-03', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (192, 13, 287, 3, '2025-04-13', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (193, 6, 378, 8, '2024-06-29', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (194, 11, 91, 4, '2024-06-19', 'Whole Foods');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (195, 10, 248, 5, '2024-12-07', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (196, 1, 129, 1, '2024-12-27', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (197, 6, 113, 4, '2025-01-11', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (198, 12, 168, 3, '2025-04-08', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (199, 8, 57, 5, '2025-02-21', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (200, 2, 93, 3, '2025-01-17', 'Whole Foods');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (201, 4, 180, 1, '2024-09-03', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (202, 9, 166, 3, '2025-01-06', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (203, 10, 474, 4, '2025-04-02', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (204, 7, 139, 3, '2024-10-22', 'Costco');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (205, 14, 492, 8, '2024-10-27', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (206, 7, 204, 6, '2024-08-17', 'CVS');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (207, 8, 74, 1, '2024-10-04', 'Costco');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (208, 10, 441, 9, '2024-06-10', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (209, 8, 41, 2, '2024-09-24', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (210, 3, 239, 1, '2024-10-11', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (211, 5, 60, 9, '2024-09-27', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (212, 3, 203, 5, '2024-12-31', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (213, 14, 40, 8, '2024-12-21', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (214, 10, 261, 2, '2024-12-31', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (215, 13, 9, 5, '2024-09-30', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (216, 9, 183, 7, '2025-03-04', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (217, 11, 355, 5, '2024-07-12', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (218, 10, 49, 10, '2024-06-26', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (219, 7, 123, 10, '2025-03-21', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (220, 11, 26, 8, '2025-01-14', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (221, 2, 463, 1, '2024-10-24', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (222, 6, 285, 3, '2025-01-12', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (223, 1, 214, 3, '2024-09-26', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (224, 1, 214, 2, '2024-10-01', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (225, 7, 387, 6, '2024-12-29', 'CVS');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (226, 6, 118, 2, '2024-06-14', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (227, 1, 161, 1, '2024-12-02', 'CVS');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (228, 2, 189, 4, '2024-08-30', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (229, 11, 473, 10, '2024-06-21', 'Whole Foods');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (230, 14, 246, 9, '2024-06-01', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (231, 1, 407, 8, '2024-12-13', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (232, 1, 357, 9, '2025-04-03', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (233, 5, 256, 2, '2025-03-18', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (234, 4, 142, 7, '2024-10-19', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (235, 10, 305, 6, '2024-09-04', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (236, 7, 362, 6, '2024-07-02', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (237, 13, 465, 5, '2024-12-17', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (238, 3, 360, 10, '2024-07-23', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (239, 10, 73, 2, '2024-09-30', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (240, 10, 398, 6, '2025-04-04', 'Whole Foods');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (241, 4, 379, 8, '2024-09-14', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (242, 14, 67, 1, '2024-07-08', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (243, 8, 118, 1, '2024-09-06', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (244, 8, 15, 9, '2025-03-02', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (245, 3, 466, 4, '2024-08-30', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (246, 3, 148, 10, '2025-02-18', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (247, 11, 447, 2, '2025-04-14', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (248, 5, 99, 1, '2024-07-17', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (249, 9, 100, 1, '2025-01-10', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (250, 3, 202, 2, '2025-03-10', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (251, 12, 423, 2, '2024-08-10', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (252, 15, 417, 7, '2025-04-07', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (253, 15, 43, 6, '2024-10-08', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (254, 4, 153, 5, '2025-03-13', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (255, 10, 269, 9, '2025-03-17', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (256, 10, 30, 9, '2024-09-28', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (257, 3, 384, 3, '2024-11-22', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (258, 6, 6, 4, '2024-09-13', 'Whole Foods');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (259, 1, 324, 9, '2025-01-05', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (260, 4, 485, 9, '2025-02-08', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (261, 8, 385, 1, '2025-03-25', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (262, 9, 313, 5, '2024-09-09', 'CVS');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (263, 6, 372, 10, '2024-11-18', 'Macy’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (264, 12, 189, 1, '2024-11-28', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (265, 7, 146, 1, '2024-06-09', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (266, 7, 471, 3, '2025-02-16', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (267, 5, 83, 6, '2024-12-04', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (268, 6, 432, 1, '2025-01-27', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (269, 12, 50, 7, '2024-11-22', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (270, 7, 159, 7, '2024-07-29', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (271, 12, 85, 4, '2024-12-01', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (272, 13, 425, 9, '2025-03-30', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (273, 11, 80, 1, '2024-12-15', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (274, 6, 379, 4, '2025-01-04', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (275, 8, 451, 3, '2024-10-18', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (276, 7, 107, 7, '2024-09-09', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (277, 6, 381, 8, '2024-10-23', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (278, 10, 52, 9, '2024-10-16', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (279, 6, 234, 5, '2024-07-07', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (280, 3, 36, 9, '2024-08-17', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (281, 2, 473, 1, '2024-08-05', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (282, 10, 54, 5, '2024-07-23', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (283, 8, 270, 6, '2024-06-25', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (284, 8, 359, 2, '2024-09-04', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (285, 14, 180, 9, '2024-06-28', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (286, 9, 20, 8, '2024-10-05', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (287, 4, 373, 10, '2024-09-05', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (288, 9, 31, 10, '2024-09-30', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (289, 13, 461, 5, '2025-01-31', 'Costco');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (290, 15, 98, 2, '2024-11-19', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (291, 3, 225, 1, '2024-12-08', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (292, 3, 126, 8, '2025-01-12', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (293, 14, 459, 7, '2024-12-08', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (294, 8, 425, 3, '2025-03-02', 'Best Buy');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (295, 13, 18, 7, '2024-10-07', 'CVS');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (296, 4, 439, 2, '2024-06-03', 'Costco');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (297, 14, 423, 10, '2025-02-13', 'Whole Foods');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (298, 14, 277, 4, '2024-07-27', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (299, 8, 6, 8, '2024-12-30', 'Kroger');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (300, 6, 272, 5, '2025-04-05', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (301, 3, 137.54, 8, '2024-10-20', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (302, 1, 432.34, 7, '2024-12-27', 'Marshalls');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (304, 4, 325.36, 3, '2024-05-31', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (305, 1, 957.54, 3, '2024-04-26', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (307, 4, 430.17, 4, '2024-04-29', 'Sephora');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (310, 3, 44.54, 5, '2025-01-03', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (311, 3, 438.68, 8, '2025-04-04', 'IKEA');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (312, 1, 989.24, 8, '2024-04-03', 'Costco');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (313, 1, 309.16, 3, '2025-04-07', 'Walgreens');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (314, 4, 940.66, 7, '2025-08-12', 'Ulta Beauty');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (315, 2, 67.39, 1, '2025-04-29', 'Home Depot');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (317, 4, 818.33, 5, '2025-04-18', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (318, 4, 415.79, 8, '2025-04-02', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (319, 3, 340.73, 4, '2025-04-30', 'Walmart');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (320, 3, 796.75, 5, '2025-04-08', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (321, 1, 528.38, 6, '2025-04-10', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (323, 3, 576.56, 4, '2025-04-18', 'Aldi');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (325, 2, 538.78, 7, '2025-04-13', 'Dollar General');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (328, 3, 140.21, 7, '2025-04-20', 'H-E-B');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (329, 3, 646.01, 4, '2025-04-21', 'Target');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (331, 1, 553.75, 1, '2024-04-22', 'Publix');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (332, 2, 511.44, 7, '2024-04-24', 'Lowe’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (336, 1, 785.54, 2, '2024-04-25', 'TJ Maxx');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (341, 1, 467.2, 5, '2025-04-21', 'Macy’s');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (343, 3, 975.06, 6, '2025-04-13', 'Whole Foods');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (347, 4, 842.39, 2, '2025-04-16', 'Nordstrom');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (348, 1, 114.65, 9, '2025-03-16', 'Ross');
insert into Transactions (transaction_id, user_id, transaction_amount, category_id, transaction_date, transaction_location) values (350, 2, 609.61, 5, '2025-01-25', 'Dollar General');
