insert into Income (user_id, income_source, income_amount) values (92, 'business profits', 8206);
insert into Income (user_id, income_source, income_amount) values (44, 'rental income', 3417);
insert into Income (user_id, income_source, income_amount) values (5, 'business profits', 8538);
insert into Income (user_id, income_source, income_amount) values (100, 'business profits', 7012);
insert into Income (user_id, income_source, income_amount) values (10, 'freelance work', 8778);
insert into Income (user_id, income_source, income_amount) values (54, 'salary', 7988);
insert into Income (user_id, income_source, income_amount) values (45, 'rental income', 7630);
insert into Income (user_id, income_source, income_amount) values (33, 'rental income', 1378);
insert into Income (user_id, income_source, income_amount) values (93, 'investment', 9921);
insert into Income (user_id, income_source, income_amount) values (88, 'investment', 2847);
insert into Income (user_id, income_source, income_amount) values (19, 'investment', 154);
insert into Income (user_id, income_source, income_amount) values (91, 'business profits', 9374);
insert into Income (user_id, income_source, income_amount) values (92, 'investment', 5458);
insert into Income (user_id, income_source, income_amount) values (86, 'investment', 1518);
insert into Income (user_id, income_source, income_amount) values (64, 'rental income', 2958);
insert into Income (user_id, income_source, income_amount) values (66, 'salary', 8553);
insert into Income (user_id, income_source, income_amount) values (28, 'rental income', 378);
insert into Income (user_id, income_source, income_amount) values (17, 'salary', 8286);
insert into Income (user_id, income_source, income_amount) values (53, 'salary', 5979);
insert into Income (user_id, income_source, income_amount) values (31, 'business profits', 954);
insert into Income (user_id, income_source, income_amount) values (86, 'salary', 6628);
insert into Income (user_id, income_source, income_amount) values (96, 'business profits', 6264);
insert into Income (user_id, income_source, income_amount) values (33, 'salary', 4091);
insert into Income (user_id, income_source, income_amount) values (65, 'salary', 8451);
insert into Income (user_id, income_source, income_amount) values (49, 'rental income', 4036);
insert into Income (user_id, income_source, income_amount) values (18, 'business profits', 9722);
insert into Income (user_id, income_source, income_amount) values (76, 'salary', 5900);
insert into Income (user_id, income_source, income_amount) values (8, 'salary', 5000);
insert into Income (user_id, income_source, income_amount) values (60, 'salary', 743);
insert into Income (user_id, income_source, income_amount) values (42, 'freelance work', 6289);
insert into Income (user_id, income_source, income_amount) values (2, 'freelance work', 2379);
insert into Income (user_id, income_source, income_amount) values (41, 'salary', 6432);
insert into Income (user_id, income_source, income_amount) values (84, 'business profits', 6535);
insert into Income (user_id, income_source, income_amount) values (37, 'business profits', 8110);
insert into Income (user_id, income_source, income_amount) values (54, 'freelance work', 1945);
insert into Income (user_id, income_source, income_amount) values (90, 'business profits', 8128);
insert into Income (user_id, income_source, income_amount) values (20, 'investment', 7386);
insert into Income (user_id, income_source, income_amount) values (98, 'salary', 5324);
insert into Income (user_id, income_source, income_amount) values (69, 'business profits', 8583);
insert into Income (user_id, income_source, income_amount) values (7, 'salary', 9748);
insert into Income (user_id, income_source, income_amount) values (37, 'business profits', 9538);
insert into Income (user_id, income_source, income_amount) values (85, 'business profits', 7419);
insert into Income (user_id, income_source, income_amount) values (13, 'freelance work', 1874);
insert into Income (user_id, income_source, income_amount) values (69, 'rental income', 111);
insert into Income (user_id, income_source, income_amount) values (6, 'business profits', 4920);
insert into Income (user_id, income_source, income_amount) values (63, 'rental income', 5489);
insert into Income (user_id, income_source, income_amount) values (9, 'rental income', 1419);
insert into Income (user_id, income_source, income_amount) values (61, 'rental income', 1295);
insert into Income (user_id, income_source, income_amount) values (37, 'freelance work', 1840);
insert into Income (user_id, income_source, income_amount) values (43, 'rental income', 811);
insert into Income (user_id, income_source, income_amount) values (28, 'investment', 3157);
insert into Income (user_id, income_source, income_amount) values (51, 'salary', 6497);
insert into Income (user_id, income_source, income_amount) values (94, 'rental income', 8346);
insert into Income (user_id, income_source, income_amount) values (97, 'business profits', 360);
insert into Income (user_id, income_source, income_amount) values (44, 'freelance work', 1193);
insert into Income (user_id, income_source, income_amount) values (45, 'rental income', 1756);
insert into Income (user_id, income_source, income_amount) values (26, 'salary', 1615);
insert into Income (user_id, income_source, income_amount) values (93, 'salary', 6301);
insert into Income (user_id, income_source, income_amount) values (76, 'salary', 6561);
insert into Income (user_id, income_source, income_amount) values (36, 'freelance work', 9660);
insert into Income (user_id, income_source, income_amount) values (67, 'salary', 944);
insert into Income (user_id, income_source, income_amount) values (58, 'investment', 8941);
insert into Income (user_id, income_source, income_amount) values (46, 'rental income', 7510);
insert into Income (user_id, income_source, income_amount) values (100, 'rental income', 540);
insert into Income (user_id, income_source, income_amount) values (60, 'investment', 5022);
insert into Income (user_id, income_source, income_amount) values (4, 'business profits', 531);
insert into Income (user_id, income_source, income_amount) values (73, 'rental income', 3123);
insert into Income (user_id, income_source, income_amount) values (78, 'freelance work', 62);
insert into Income (user_id, income_source, income_amount) values (5, 'rental income', 7599);
insert into Income (user_id, income_source, income_amount) values (29, 'freelance work', 7579);
insert into Income (user_id, income_source, income_amount) values (30, 'business profits', 5036);
insert into Income (user_id, income_source, income_amount) values (35, 'salary', 5823);
insert into Income (user_id, income_source, income_amount) values (11, 'rental income', 6919);
insert into Income (user_id, income_source, income_amount) values (46, 'freelance work', 1429);
insert into Income (user_id, income_source, income_amount) values (22, 'business profits', 5820);
insert into Income (user_id, income_source, income_amount) values (45, 'salary', 4725);
insert into Income (user_id, income_source, income_amount) values (72, 'rental income', 4452);
insert into Income (user_id, income_source, income_amount) values (77, 'rental income', 6921);
insert into Income (user_id, income_source, income_amount) values (36, 'salary', 4598);
insert into Income (user_id, income_source, income_amount) values (21, 'salary', 8739);
insert into Income (user_id, income_source, income_amount) values (22, 'freelance work', 1462);
insert into Income (user_id, income_source, income_amount) values (8, 'freelance work', 947);
insert into Income (user_id, income_source, income_amount) values (43, 'business profits', 2483);
insert into Income (user_id, income_source, income_amount) values (61, 'rental income', 5270);
insert into Income (user_id, income_source, income_amount) values (37, 'salary', 4593);
insert into Income (user_id, income_source, income_amount) values (96, 'business profits', 3230);
insert into Income (user_id, income_source, income_amount) values (51, 'freelance work', 5323);
insert into Income (user_id, income_source, income_amount) values (11, 'freelance work', 6486);
insert into Income (user_id, income_source, income_amount) values (75, 'rental income', 5304);
insert into Income (user_id, income_source, income_amount) values (40, 'business profits', 979);
insert into Income (user_id, income_source, income_amount) values (28, 'investment', 8055);
insert into Income (user_id, income_source, income_amount) values (79, 'rental income', 5904);
insert into Income (user_id, income_source, income_amount) values (80, 'freelance work', 2624);
insert into Income (user_id, income_source, income_amount) values (51, 'freelance work', 8879);
insert into Income (user_id, income_source, income_amount) values (53, 'rental income', 675);
insert into Income (user_id, income_source, income_amount) values (91, 'investment', 6206);
insert into Income (user_id, income_source, income_amount) values (66, 'investment', 3278);
insert into Income (user_id, income_source, income_amount) values (81, 'freelance work', 6686);
insert into Income (user_id, income_source, income_amount) values (96, 'business profits', 2894);
insert into Income (user_id, income_source, income_amount) values (94, 'business profits', 3184);
insert into Income (user_id, income_source, income_amount) values (68, 'business profits', 1193);
insert into Income (user_id, income_source, income_amount) values (79, 'freelance work', 6215);
insert into Income (user_id, income_source, income_amount) values (56, 'salary', 2947);
insert into Income (user_id, income_source, income_amount) values (64, 'investment', 4461);
insert into Income (user_id, income_source, income_amount) values (44, 'salary', 6950);
insert into Income (user_id, income_source, income_amount) values (71, 'business profits', 793);
insert into Income (user_id, income_source, income_amount) values (20, 'investment', 4960);
insert into Income (user_id, income_source, income_amount) values (10, 'investment', 9555);
insert into Income (user_id, income_source, income_amount) values (34, 'rental income', 8267);
insert into Income (user_id, income_source, income_amount) values (43, 'salary', 2948);
insert into Income (user_id, income_source, income_amount) values (73, 'investment', 9810);
insert into Income (user_id, income_source, income_amount) values (3, 'freelance work', 6692);
insert into Income (user_id, income_source, income_amount) values (46, 'business profits', 4261);
insert into Income (user_id, income_source, income_amount) values (37, 'business profits', 4602);
insert into Income (user_id, income_source, income_amount) values (48, 'salary', 1854);
insert into Income (user_id, income_source, income_amount) values (73, 'freelance work', 1735);
insert into Income (user_id, income_source, income_amount) values (99, 'business profits', 8338);
insert into Income (user_id, income_source, income_amount) values (3, 'rental income', 72);
insert into Income (user_id, income_source, income_amount) values (71, 'freelance work', 1233);
insert into Income (user_id, income_source, income_amount) values (62, 'rental income', 63);
insert into Income (user_id, income_source, income_amount) values (71, 'salary', 8996);
insert into Income (user_id, income_source, income_amount) values (97, 'salary', 7590);
insert into Income (user_id, income_source, income_amount) values (15, 'business profits', 4043);
insert into Income (user_id, income_source, income_amount) values (66, 'investment', 5959);
insert into Income (user_id, income_source, income_amount) values (22, 'investment', 5126);
insert into Income (user_id, income_source, income_amount) values (79, 'freelance work', 2987);
insert into Income (user_id, income_source, income_amount) values (96, 'freelance work', 9315);
insert into Income (user_id, income_source, income_amount) values (97, 'freelance work', 283);
insert into Income (user_id, income_source, income_amount) values (38, 'salary', 4268);
insert into Income (user_id, income_source, income_amount) values (79, 'salary', 3029);
insert into Income (user_id, income_source, income_amount) values (20, 'salary', 1677);
insert into Income (user_id, income_source, income_amount) values (59, 'business profits', 1524);
insert into Income (user_id, income_source, income_amount) values (31, 'business profits', 2772);
insert into Income (user_id, income_source, income_amount) values (54, 'investment', 6943);
insert into Income (user_id, income_source, income_amount) values (78, 'freelance work', 6583);
insert into Income (user_id, income_source, income_amount) values (43, 'business profits', 1318);
insert into Income (user_id, income_source, income_amount) values (68, 'salary', 1807);
insert into Income (user_id, income_source, income_amount) values (70, 'investment', 2162);
insert into Income (user_id, income_source, income_amount) values (62, 'business profits', 9350);
insert into Income (user_id, income_source, income_amount) values (31, 'investment', 1648);
insert into Income (user_id, income_source, income_amount) values (18, 'freelance work', 5655);
insert into Income (user_id, income_source, income_amount) values (76, 'salary', 1420);
insert into Income (user_id, income_source, income_amount) values (36, 'salary', 435);
insert into Income (user_id, income_source, income_amount) values (89, 'business profits', 1794);
insert into Income (user_id, income_source, income_amount) values (34, 'investment', 9519);
insert into Income (user_id, income_source, income_amount) values (48, 'rental income', 370);
insert into Income (user_id, income_source, income_amount) values (52, 'business profits', 1603);
insert into Income (user_id, income_source, income_amount) values (91, 'business profits', 2125);
insert into Income (user_id, income_source, income_amount) values (60, 'investment', 3475);
insert into Income (user_id, income_source, income_amount) values (23, 'rental income', 6778);
insert into Income (user_id, income_source, income_amount) values (5, 'freelance work', 6997);
insert into Income (user_id, income_source, income_amount) values (89, 'investment', 5463);
insert into Income (user_id, income_source, income_amount) values (96, 'rental income', 8231);
insert into Income (user_id, income_source, income_amount) values (98, 'business profits', 7960);
insert into Income (user_id, income_source, income_amount) values (64, 'rental income', 6272);
insert into Income (user_id, income_source, income_amount) values (17, 'salary', 9942);
insert into Income (user_id, income_source, income_amount) values (49, 'investment', 3139);
insert into Income (user_id, income_source, income_amount) values (60, 'business profits', 4272);
insert into Income (user_id, income_source, income_amount) values (42, 'rental income', 7420);
insert into Income (user_id, income_source, income_amount) values (44, 'investment', 8330);
insert into Income (user_id, income_source, income_amount) values (87, 'salary', 4341);
insert into Income (user_id, income_source, income_amount) values (95, 'salary', 2768);
insert into Income (user_id, income_source, income_amount) values (83, 'freelance work', 7339);
insert into Income (user_id, income_source, income_amount) values (84, 'business profits', 1741);
insert into Income (user_id, income_source, income_amount) values (5, 'salary', 9285);
insert into Income (user_id, income_source, income_amount) values (57, 'freelance work', 5369);
insert into Income (user_id, income_source, income_amount) values (71, 'investment', 1342);
insert into Income (user_id, income_source, income_amount) values (91, 'business profits', 3378);
insert into Income (user_id, income_source, income_amount) values (23, 'rental income', 651);
insert into Income (user_id, income_source, income_amount) values (66, 'rental income', 2048);
insert into Income (user_id, income_source, income_amount) values (81, 'business profits', 6645);
insert into Income (user_id, income_source, income_amount) values (50, 'business profits', 179);
insert into Income (user_id, income_source, income_amount) values (86, 'salary', 1768);
insert into Income (user_id, income_source, income_amount) values (89, 'salary', 6352);
insert into Income (user_id, income_source, income_amount) values (38, 'investment', 2373);
insert into Income (user_id, income_source, income_amount) values (93, 'investment', 8199);
insert into Income (user_id, income_source, income_amount) values (90, 'salary', 1803);
insert into Income (user_id, income_source, income_amount) values (67, 'investment', 2752);
insert into Income (user_id, income_source, income_amount) values (50, 'business profits', 9137);
insert into Income (user_id, income_source, income_amount) values (49, 'rental income', 2807);
insert into Income (user_id, income_source, income_amount) values (100, 'salary', 7894);
insert into Income (user_id, income_source, income_amount) values (11, 'salary', 9698);
insert into Income (user_id, income_source, income_amount) values (27, 'rental income', 6883);
insert into Income (user_id, income_source, income_amount) values (94, 'freelance work', 2500);
insert into Income (user_id, income_source, income_amount) values (88, 'business profits', 2462);
insert into Income (user_id, income_source, income_amount) values (57, 'salary', 5328);
insert into Income (user_id, income_source, income_amount) values (82, 'freelance work', 4824);
insert into Income (user_id, income_source, income_amount) values (72, 'business profits', 8817);
insert into Income (user_id, income_source, income_amount) values (52, 'rental income', 3922);
insert into Income (user_id, income_source, income_amount) values (6, 'rental income', 3509);
insert into Income (user_id, income_source, income_amount) values (46, 'investment', 5771);
insert into Income (user_id, income_source, income_amount) values (79, 'freelance work', 5185);
insert into Income (user_id, income_source, income_amount) values (3, 'salary', 3237);
insert into Income (user_id, income_source, income_amount) values (99, 'freelance work', 6832);
insert into Income (user_id, income_source, income_amount) values (25, 'salary', 611);
insert into Income (user_id, income_source, income_amount) values (9, 'salary', 9995);
insert into Income (user_id, income_source, income_amount) values (3, 'freelance work', 7152);
insert into Income (user_id, income_source, income_amount) values (42, 'freelance work', 1948);
insert into Income (user_id, income_source, income_amount) values (52, 'business profits', 1851);
insert into Income (user_id, income_source, income_amount) values (64, 'rental income', 9581);
insert into Income (user_id, income_source, income_amount) values (98, 'business profits', 3413);
insert into Income (user_id, income_source, income_amount) values (71, 'business profits', 2766);
insert into Income (user_id, income_source, income_amount) values (43, 'investment', 3921);
insert into Income (user_id, income_source, income_amount) values (58, 'investment', 4457);
insert into Income (user_id, income_source, income_amount) values (71, 'investment', 4065);
insert into Income (user_id, income_source, income_amount) values (42, 'investment', 5556);
insert into Income (user_id, income_source, income_amount) values (97, 'freelance work', 5483);
insert into Income (user_id, income_source, income_amount) values (86, 'investment', 4632);
insert into Income (user_id, income_source, income_amount) values (34, 'investment', 1872);
insert into Income (user_id, income_source, income_amount) values (17, 'freelance work', 1510);
insert into Income (user_id, income_source, income_amount) values (64, 'rental income', 2259);
insert into Income (user_id, income_source, income_amount) values (42, 'freelance work', 1450);
insert into Income (user_id, income_source, income_amount) values (11, 'freelance work', 9168);
insert into Income (user_id, income_source, income_amount) values (29, 'investment', 2539);
insert into Income (user_id, income_source, income_amount) values (44, 'rental income', 4674);
insert into Income (user_id, income_source, income_amount) values (9, 'salary', 6404);
insert into Income (user_id, income_source, income_amount) values (22, 'rental income', 1349);
insert into Income (user_id, income_source, income_amount) values (58, 'rental income', 4482);
insert into Income (user_id, income_source, income_amount) values (10, 'salary', 3749);
insert into Income (user_id, income_source, income_amount) values (61, 'rental income', 6189);
insert into Income (user_id, income_source, income_amount) values (46, 'business profits', 6836);
insert into Income (user_id, income_source, income_amount) values (93, 'salary', 4831);
insert into Income (user_id, income_source, income_amount) values (3, 'salary', 3914);
insert into Income (user_id, income_source, income_amount) values (47, 'business profits', 3927);
insert into Income (user_id, income_source, income_amount) values (41, 'rental income', 2473);
insert into Income (user_id, income_source, income_amount) values (53, 'business profits', 4581);
insert into Income (user_id, income_source, income_amount) values (20, 'rental income', 11);
insert into Income (user_id, income_source, income_amount) values (70, 'rental income', 7663);
insert into Income (user_id, income_source, income_amount) values (74, 'salary', 8497);
insert into Income (user_id, income_source, income_amount) values (60, 'investment', 5502);
insert into Income (user_id, income_source, income_amount) values (46, 'business profits', 4067);
insert into Income (user_id, income_source, income_amount) values (17, 'business profits', 6566);
insert into Income (user_id, income_source, income_amount) values (53, 'freelance work', 1090);
insert into Income (user_id, income_source, income_amount) values (30, 'freelance work', 4557);
insert into Income (user_id, income_source, income_amount) values (76, 'salary', 2242);
insert into Income (user_id, income_source, income_amount) values (98, 'business profits', 6096);
insert into Income (user_id, income_source, income_amount) values (8, 'business profits', 7356);
insert into Income (user_id, income_source, income_amount) values (78, 'investment', 7402);
insert into Income (user_id, income_source, income_amount) values (64, 'salary', 659);
insert into Income (user_id, income_source, income_amount) values (60, 'investment', 5049);
insert into Income (user_id, income_source, income_amount) values (30, 'salary', 4048);
insert into Income (user_id, income_source, income_amount) values (21, 'salary', 2256);
insert into Income (user_id, income_source, income_amount) values (55, 'investment', 6549);
insert into Income (user_id, income_source, income_amount) values (95, 'rental income', 5396);
insert into Income (user_id, income_source, income_amount) values (68, 'freelance work', 7402);
insert into Income (user_id, income_source, income_amount) values (37, 'salary', 7326);
insert into Income (user_id, income_source, income_amount) values (43, 'salary', 3149);
insert into Income (user_id, income_source, income_amount) values (63, 'salary', 8378);
insert into Income (user_id, income_source, income_amount) values (27, 'business profits', 107);
insert into Income (user_id, income_source, income_amount) values (61, 'salary', 5320);
insert into Income (user_id, income_source, income_amount) values (11, 'business profits', 1840);
insert into Income (user_id, income_source, income_amount) values (5, 'investment', 1323);
insert into Income (user_id, income_source, income_amount) values (1, 'freelance work', 7373);
insert into Income (user_id, income_source, income_amount) values (90, 'business profits', 2981);
insert into Income (user_id, income_source, income_amount) values (16, 'business profits', 6362);
insert into Income (user_id, income_source, income_amount) values (96, 'rental income', 3070);
insert into Income (user_id, income_source, income_amount) values (75, 'investment', 8335);
insert into Income (user_id, income_source, income_amount) values (47, 'investment', 7622);
insert into Income (user_id, income_source, income_amount) values (69, 'rental income', 8105);
insert into Income (user_id, income_source, income_amount) values (60, 'rental income', 5728);
insert into Income (user_id, income_source, income_amount) values (71, 'investment', 7054);
insert into Income (user_id, income_source, income_amount) values (42, 'rental income', 5053);
insert into Income (user_id, income_source, income_amount) values (90, 'investment', 9553);
insert into Income (user_id, income_source, income_amount) values (75, 'freelance work', 2544);
insert into Income (user_id, income_source, income_amount) values (15, 'business profits', 8161);
insert into Income (user_id, income_source, income_amount) values (36, 'investment', 5375);
insert into Income (user_id, income_source, income_amount) values (40, 'rental income', 275);
insert into Income (user_id, income_source, income_amount) values (9, 'freelance work', 7874);
insert into Income (user_id, income_source, income_amount) values (11, 'business profits', 6055);
insert into Income (user_id, income_source, income_amount) values (94, 'investment', 6759);
insert into Income (user_id, income_source, income_amount) values (2, 'salary', 6185);
insert into Income (user_id, income_source, income_amount) values (12, 'freelance work', 2894);
insert into Income (user_id, income_source, income_amount) values (7, 'salary', 2287);
insert into Income (user_id, income_source, income_amount) values (39, 'freelance work', 7996);
insert into Income (user_id, income_source, income_amount) values (80, 'salary', 5209);
insert into Income (user_id, income_source, income_amount) values (1, 'investment', 4171);
insert into Income (user_id, income_source, income_amount) values (18, 'business profits', 7235);
insert into Income (user_id, income_source, income_amount) values (67, 'business profits', 9512);
insert into Income (user_id, income_source, income_amount) values (50, 'investment', 5539);
insert into Income (user_id, income_source, income_amount) values (80, 'rental income', 1942);
insert into Income (user_id, income_source, income_amount) values (60, 'rental income', 9114);
insert into Income (user_id, income_source, income_amount) values (53, 'investment', 2563);
insert into Income (user_id, income_source, income_amount) values (75, 'investment', 4490);
insert into Income (user_id, income_source, income_amount) values (10, 'freelance work', 7522);
insert into Income (user_id, income_source, income_amount) values (81, 'business profits', 4932);
insert into Income (user_id, income_source, income_amount) values (19, 'investment', 1056);
insert into Income (user_id, income_source, income_amount) values (57, 'investment', 4331);
insert into Income (user_id, income_source, income_amount) values (72, 'rental income', 1328);
insert into Income (user_id, income_source, income_amount) values (3, 'salary', 2662);
insert into Income (user_id, income_source, income_amount) values (90, 'freelance work', 1628);
insert into Income (user_id, income_source, income_amount) values (42, 'freelance work', 5756);
insert into Income (user_id, income_source, income_amount) values (33, 'business profits', 7135);
insert into Income (user_id, income_source, income_amount) values (16, 'investment', 6688);
insert into Income (user_id, income_source, income_amount) values (4, 'business profits', 506);
insert into Income (user_id, income_source, income_amount) values (82, 'business profits', 8752);
insert into Income (user_id, income_source, income_amount) values (12, 'business profits', 5515);
insert into Income (user_id, income_source, income_amount) values (93, 'investment', 7964);
insert into Income (user_id, income_source, income_amount) values (11, 'freelance work', 7747);
insert into Income (user_id, income_source, income_amount) values (68, 'freelance work', 8210);
insert into Income (user_id, income_source, income_amount) values (64, 'business profits', 704);
insert into Income (user_id, income_source, income_amount) values (22, 'investment', 4876);
insert into Income (user_id, income_source, income_amount) values (80, 'business profits', 1541);
insert into Income (user_id, income_source, income_amount) values (43, 'investment', 3459);
insert into Income (user_id, income_source, income_amount) values (18, 'business profits', 9042);
insert into Income (user_id, income_source, income_amount) values (7, 'salary', 5968);
insert into Income (user_id, income_source, income_amount) values (43, 'freelance work', 254);
insert into Income (user_id, income_source, income_amount) values (2, 'freelance work', 9968);
insert into Income (user_id, income_source, income_amount) values (82, 'investment', 2786);
insert into Income (user_id, income_source, income_amount) values (21, 'salary', 951);
insert into Income (user_id, income_source, income_amount) values (55, 'business profits', 7065);
insert into Income (user_id, income_source, income_amount) values (3, 'salary', 4438);
insert into Income (user_id, income_source, income_amount) values (97, 'investment', 9301);
insert into Income (user_id, income_source, income_amount) values (30, 'salary', 9808);
insert into Income (user_id, income_source, income_amount) values (75, 'rental income', 6728);
insert into Income (user_id, income_source, income_amount) values (33, 'business profits', 1322);
insert into Income (user_id, income_source, income_amount) values (58, 'business profits', 8154);
insert into Income (user_id, income_source, income_amount) values (7, 'investment', 345);
insert into Income (user_id, income_source, income_amount) values (93, 'business profits', 2423);
insert into Income (user_id, income_source, income_amount) values (6, 'business profits', 7694);
insert into Income (user_id, income_source, income_amount) values (33, 'rental income', 8469);
insert into Income (user_id, income_source, income_amount) values (70, 'investment', 3746);
insert into Income (user_id, income_source, income_amount) values (87, 'business profits', 1979);
insert into Income (user_id, income_source, income_amount) values (99, 'freelance work', 4802);
insert into Income (user_id, income_source, income_amount) values (34, 'investment', 3010);
insert into Income (user_id, income_source, income_amount) values (51, 'rental income', 2059);
insert into Income (user_id, income_source, income_amount) values (11, 'investment', 2671);
insert into Income (user_id, income_source, income_amount) values (76, 'freelance work', 7624);
insert into Income (user_id, income_source, income_amount) values (23, 'investment', 3618);
insert into Income (user_id, income_source, income_amount) values (94, 'investment', 4045);
insert into Income (user_id, income_source, income_amount) values (37, 'salary', 6683);
insert into Income (user_id, income_source, income_amount) values (9, 'freelance work', 8758);
insert into Income (user_id, income_source, income_amount) values (68, 'investment', 7998);
insert into Income (user_id, income_source, income_amount) values (92, 'freelance work', 1448);
insert into Income (user_id, income_source, income_amount) values (13, 'rental income', 2562);
insert into Income (user_id, income_source, income_amount) values (18, 'freelance work', 6127);
insert into Income (user_id, income_source, income_amount) values (83, 'rental income', 9225);
insert into Income (user_id, income_source, income_amount) values (13, 'salary', 1487);
insert into Income (user_id, income_source, income_amount) values (19, 'rental income', 2992);
insert into Income (user_id, income_source, income_amount) values (25, 'investment', 7216);
insert into Income (user_id, income_source, income_amount) values (10, 'rental income', 5807);
insert into Income (user_id, income_source, income_amount) values (46, 'freelance work', 6146);
insert into Income (user_id, income_source, income_amount) values (92, 'rental income', 3911);
insert into Income (user_id, income_source, income_amount) values (69, 'rental income', 455);
insert into Income (user_id, income_source, income_amount) values (22, 'business profits', 6569);
insert into Income (user_id, income_source, income_amount) values (18, 'salary', 2011);
insert into Income (user_id, income_source, income_amount) values (24, 'freelance work', 2333);
insert into Income (user_id, income_source, income_amount) values (68, 'investment', 4237);
insert into Income (user_id, income_source, income_amount) values (93, 'investment', 1767);
insert into Income (user_id, income_source, income_amount) values (56, 'salary', 6269);
insert into Income (user_id, income_source, income_amount) values (53, 'investment', 5992);
